In [20]:
import pandas as pd 
df=pd.read_csv('train (1).csv',usecols=['Age','Fare','Survived'])

In [21]:
from sklearn.model_selection import train_test_split 
x=df.iloc[:,0:2]
y=df.iloc[:,-1]

x_train,x_test,y_train,y_test=train_test_split (x,y)
x_train

     Survived   Age
148         0  36.5
765         1  51.0
196         0   NaN
662         0  47.0
580         1  25.0
..        ...   ...
514         0  24.0
379         0  19.0
240         0   NaN
325         1  36.0
137         0  37.0

[668 rows x 2 columns]

*** i will create a new column of age_imputed***

In [22]:
x_train['Age_imputed']=x_train['Age']

x_train

*** filling the na places with some random value***

In [26]:
x_train['Age'].dropna().sample(1)

261    3.0
Name: Age, dtype: float64

*** this above code gives us a single random value but***
***we want to replace all na present in age imputed column***

In [29]:
z=x_train['Age_imputed'].isnull().sum()

In [30]:
x_train['Age'].dropna().sample(z)

422    29.0
587    60.0
529    23.0
70     32.0
434    50.0
       ...
745    70.0
810    26.0
23     28.0
600    24.0
579    32.0
Name: Age, Length: 136, dtype: float64

*** above data is in series so we have to convert it into numpy array***

In [36]:
x_train['Age'].dropna().sample(z).values.shape

(136,)

In [41]:
zz=x_train['Age_imputed'].isnull()

*** it is generally copying the na value list as zz by sample list ***
*** so the list of na get replaced by sample list and is stored directily in column ["Age_imputed"] ***

In [42]:
x_train.loc[zz,'Age_imputed']=x_train['Age'].dropna().sample(z).values

In [43]:
x_train

     Survived   Age  Age_imputed
148         0  36.5         36.5
765         1  51.0         51.0
196         0   NaN         30.0
662         0  47.0         47.0
580         1  25.0         25.0
..        ...   ...          ...
514         0  24.0         24.0
379         0  19.0         19.0
240         0   NaN         39.0
325         1  36.0         36.0
137         0  37.0         37.0

[668 rows x 3 columns]

import seaborn as sns 
sns.kdeplot(x_train['Age'])
sns.kdeplot(x_train['Age_imputed'])

In [ ]:
sample_fixed_value=x_train['Age'].dropna().sample(1,random_state=int(observation['Fare']).values

*** we are filling the column with random value so during model production 
if user give input then maybe my data column will have another sample list 
so make sure it give same sample list if we pass same input ***
for example we train model by giving x_train,y_train and then two user give same input to check prediction so maybe both giving same input but random sample list be diifrent for both so make sure it to get same sample lsit for same input ***

In [53]:
df=pd.read_csv('house-train.csv',usecols=['FireplaceQu','GarageQual','SalePrice'])

In [57]:
df.isnull().mean()*100

FireplaceQu    47.260274
GarageQual      5.547945
SalePrice       0.000000
dtype: float64

In [58]:
from sklearn.model_selection import train_test_split 
x=df.iloc[:,0:2]
y=df.iloc[:,-1]

x_train,x_test,y_train,y_test=train_test_split (x,y)
x_train

    FireplaceQu GarageQual
162          Gd         TA
793         NaN         TA
604          TA         TA
597          Gd         TA
667          Fa         TA
..          ...        ...
929          TA         TA
227         NaN         TA
177          Gd         TA
217         NaN         TA
683          TA         TA

[1095 rows x 2 columns]

In [68]:
x_train['FireplaceQu_imputed']=x_train['FireplaceQu']
x_train['GarageQual_imputed']=x_train['GarageQual']

In [69]:
zzz=x_train['FireplaceQu_imputed'].isnull()

In [72]:
x_train.loc[zzz,'FireplaceQu_imputed']=x_train['FireplaceQu_imputed'].dropna().sample(x_train['FireplaceQu_imputed'].isnull().sum()).values

In [73]:
x_train

    FireplaceQu GarageQual FireplaceQu_imputed GarageQual_imputed
162          Gd         TA                  Gd                 TA
793         NaN         TA                  TA                 TA
604          TA         TA                  TA                 TA
597          Gd         TA                  Gd                 TA
667          Fa         TA                  Fa                 TA
..          ...        ...                 ...                ...
929          TA         TA                  TA                 TA
227         NaN         TA                  TA                 TA
177          Gd         TA                  Gd                 TA
217         NaN         TA                  TA                 TA
683          TA         TA                  TA                 TA

[1095 rows x 4 columns]