In [356]:
import pandas as pd 
import numpy as np
df=np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']])

***when we run all cells again then it might change again and again***

In [357]:
np.random.seed(9)
df=df.sample(5)

In [358]:
df=df.drop(columns=['Profit'])
df

    R&D Spend  Administration  Marketing Spend
21    78389.0        153773.0         299737.0
37    44070.0         51283.0         197029.0
2    153442.0        101146.0         407935.0
14   119943.0        156547.0         256513.0
44    22178.0        154806.0          28335.0

***first we will create na values***

***iloc causes changein orignial df***

In [359]:
df.iloc[1,0]=np.nan
df.iloc[3,1]=np.nan
df.iloc[4,2]=np.nan

In [360]:
df

    R&D Spend  Administration  Marketing Spend
21    78389.0        153773.0         299737.0
37        NaN         51283.0         197029.0
2    153442.0        101146.0         407935.0
14   119943.0             NaN         256513.0
44    22178.0        154806.0              NaN

***fill all the nan by mean value***

In [361]:
df0=pd.DataFrame()

In [362]:
df0['R&D Spend']=df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Marketing Spend']=df['Marketing Spend'].fillna(df['Marketing Spend'].mean())
df0['Administration']=df['Administration'].fillna(df['Administration'].mean())

In [363]:
df0
df1=df0.copy()

***replace a mean value by nan***

In [364]:
df1.iloc[1,0]=np.nan

In [365]:
df1

    R&D Spend  Marketing Spend  Administration
21    78389.0         299737.0        153773.0
37        NaN         197029.0         51283.0
2    153442.0         407935.0        101146.0
14   119943.0         256513.0        115252.0
44    22178.0         290303.5        154806.0

In [366]:
x=df1.iloc[[0,2,3,4],1:3].values
y=df1.iloc[[0,2,3,4],0]
z=df1.iloc[1,1:].values.reshape(1,2)

In [367]:
from sklearn.linear_model import LogisticRegression
li=LogisticRegression()
li.fit(x,y)
y_pred=li.predict(z)

In [368]:
y_pred

array([153442.])

In [369]:
df1.iloc[1,0]=y_pred
df1

    R&D Spend  Marketing Spend  Administration
21    78389.0         299737.0        153773.0
37   153442.0         197029.0         51283.0
2    153442.0         407935.0        101146.0
14   119943.0         256513.0        115252.0
44    22178.0         290303.5        154806.0

***now we will fill column na by help of these data***

In [371]:

y=df.iloc[[0,1,2,4],[1]].values

In [372]:
df1.iloc[3,1]=np.nan
df1
x=df1.iloc[[0,1,2,4],[0,2]].values
y=df.iloc[[0,1,2,4],[1]].values
li.fit(x,y)
y_pred=li.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/home/linuxbrew/.linuxbrew/Cellar/jupyterlab/4.5.3/libexec/lib/python3.14/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [376]:
df1.iloc[3,1]=y_pred

    R&D Spend  Marketing Spend  Administration
21    78389.0         299737.0        153773.0
37   153442.0         197029.0         51283.0
2    153442.0         407935.0        101146.0
14   119943.0         101146.0        115252.0
44    22178.0         290303.5        154806.0

In [379]:
df1.iloc[4,2]=np.nan
df1

    R&D Spend  Marketing Spend  Administration
21    78389.0         299737.0        153773.0
37   153442.0         197029.0         51283.0
2    153442.0         407935.0        101146.0
14   119943.0         101146.0        115252.0
44    22178.0         290303.5             NaN

In [384]:
x=df1.iloc[0:4,0:2].values
y=df1.iloc[0:4,-1].values
y.shape

(4,)

In [390]:
li.fit(x,y)
y_pred=li.predict(df.iloc[4,0:2].values.reshape(1,2))
df1.iloc[4,2]=y_pred
df1

    R&D Spend  Marketing Spend  Administration
21    78389.0         299737.0        153773.0
37   153442.0         197029.0         51283.0
2    153442.0         407935.0        101146.0
14   119943.0         101146.0        115252.0
44    22178.0         290303.5        153773.0

In [391]:
df1-df0

    R&D Spend  Marketing Spend  Administration
21        0.0              0.0             0.0
37    59954.0              0.0             0.0
2         0.0              0.0             0.0
14        0.0        -155367.0             0.0
44        0.0              0.0         -1033.0