In [181]:
import pandas as pd 
df=pd.read_csv('train (1).csv',usecols=['Age','Fare','Survived'])

In [182]:
df_Age=df[['Age']]

In [183]:
from sklearn.impute import MissingIndicator

In [184]:
mi=MissingIndicator()

In [185]:
df_Age_miss=mi.fit_transform(df_Age)

In [186]:
df_Age_miss=pd.DataFrame(df_Age_miss,columns=['Age_miss'])

In [187]:
df=pd.concat([df,df_Age_miss],axis=1)

In [188]:
df

     Survived   Age     Fare  Age_miss
0           0  22.0   7.2500     False
1           1  38.0  71.2833     False
2           1  26.0   7.9250     False
3           1  35.0  53.1000     False
4           0  35.0   8.0500     False
..        ...   ...      ...       ...
886         0  27.0  13.0000     False
887         1  19.0  30.0000     False
888         0   NaN  23.4500      True
889         1  26.0  30.0000     False
890         0  32.0   7.7500     False

[891 rows x 4 columns]

In [189]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
Age_miss      0
dtype: int64

In [190]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [191]:
trf=ColumnTransformer(
    transformers=[
        ('impute',SimpleImputer(),['Age']),
       
    ],remainder='passthrough')

In [192]:
dff=trf.fit_transform(df)
dff=pd.DataFrame(dff,columns=['Age','Survived','Fare','Age_miss'])
dff.isnull().sum()

Age         0
Survived    0
Fare        0
Age_miss    0
dtype: int64

In [193]:
dff

           Age Survived     Fare Age_miss
0         22.0        0     7.25    False
1         38.0        1  71.2833    False
2         26.0        1    7.925    False
3         35.0        1     53.1    False
4         35.0        0     8.05    False
..         ...      ...      ...      ...
886       27.0        0     13.0    False
887       19.0        1     30.0    False
888  29.699118        0    23.45     True
889       26.0        1     30.0    False
890       32.0        0     7.75    False

[891 rows x 4 columns]

In [194]:
dff=dff.drop(['Age_miss'],axis=1)
dff.head()

    Age Survived     Fare
0  22.0        0     7.25
1  38.0        1  71.2833
2  26.0        1    7.925
3  35.0        1     53.1
4  35.0        0     8.05

In [195]:
dff

           Age Survived     Fare
0         22.0        0     7.25
1         38.0        1  71.2833
2         26.0        1    7.925
3         35.0        1     53.1
4         35.0        0     8.05
..         ...      ...      ...
886       27.0        0     13.0
887       19.0        1     30.0
888  29.699118        0    23.45
889       26.0        1     30.0
890       32.0        0     7.75

[891 rows x 3 columns]

In [196]:
from sklearn.model_selection import train_test_split
x=dff[['Age','Fare']]
y=dff[['Survived']]
# x_train,x_test,y_train,y_test=train_test_split (x,y)
x_train
y_train

In [201]:
x_train

           Age     Fare
674  29.699118      0.0
344       36.0     13.0
877       19.0   7.8958
393       23.0  113.275
7          2.0   21.075
..         ...      ...
590       35.0    7.125
438       64.0    263.0
702       18.0  14.4542
248       37.0  52.5542
388  29.699118   7.7292

[668 rows x 2 columns]

In [216]:
from sklearn.linear_model import LinearRegression 
li= LinearRegression ()

In [217]:
x_train 
y_train=pd.DataFrame(y_train,columns=['Survived'])

In [218]:
y_train

    Survived
0          0
1          0
2          0
3          1
4          0
..       ...
663        0
664        0
665        0
666        1
667        0

[668 rows x 1 columns]

In [219]:
li.fit(x_train,y_train)

LinearRegression()

In [220]:
from sklearn.metrics import accuracy_score

In [228]:
y_test=pd.DataFrame(y_test,columns=['Survived'])

In [229]:
y_test

    Survived
339        0
501        0
731        0
110        0
325        1
..       ...
550        1
30         0
185        0
442        0
811        0

[223 rows x 1 columns]

In [232]:
y_pred=clf.predict(x_test)
y_pred=pd.DataFrame(y_pred,columns=['Survived'])
y_pred
print('accuracy_score',accuracy_score(y_pred,y_test))

ValueError: Classification metrics can't handle a mix of continuous and unknown targets